# Setup

In [1]:
#Install required packages
!pip install pandas numpy 
!pip install lxml

Requirement already satisfied: pandas in ./opt/anaconda3/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.9/site-packages (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in ./opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./opt/anaconda3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: lxml in ./opt/anaconda3/lib/python3.9/site-packages (4.8.0)

# Importing Required Libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
#suppress warnings generated by the code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# Extract the required GDP data from the given URL using Web Scraping.

In [4]:
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

In [7]:
# Extract tables from webpage using Pandas. Retain table number 3 as the required dataframe.
tables = pd.read_html(URL)
df = tables[3]

In [9]:
# Replace the column headers with column numbers
df.columns = range(df.shape[1])
df

,0,1,2,3,4,5,6,7
0,World,—,105568776,2023,100562011,2022,96698005,2021
1,United States,Americas,26854599,2023,25462700,2022,23315081,2021
2,China,Asia,19373586,[n 1]2023,17963171,[n 3]2022,17734131,[n 1]2021
3,Japan,Asia,4409738,2023,4231141,2022,4940878,2021
4,Germany,Europe,4308854,2023,4072192,2022,4259935,2021
...,...,...,...,...,...,...,...,...
209,Anguilla,Americas,—,—,—,—,303,2021
210,Kiribati,Oceania,248,2023,223,2022,227,2021
211,Nauru,Oceania,151,2023,151,2022,155,2021
212,Montserrat,Americas,—,—,—,—,72,2021
213,Tuvalu,Oceania,65,2023,60,2022,60,2021

In [11]:
# Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
df = df[[0,2]]
df

                 0          2
0            World  105568776
1    United States   26854599
2            China   19373586
3            Japan    4409738
4          Germany    4308854
..             ...        ...
209       Anguilla          —
210       Kiribati        248
211          Nauru        151
212     Montserrat          —
213         Tuvalu         65

[214 rows x 2 columns]

In [14]:
# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
df = df.iloc[1:11,:]
df

                 0         2
1    United States  26854599
2            China  19373586
3            Japan   4409738
4          Germany   4308854
5            India   3736882
6   United Kingdom   3158938
7           France   2923489
8            Italy   2169745
9           Canada   2089672
10          Brazil   2081235

In [16]:
# Assign column names as "Country" and "GDP (Million USD)"
df.columns = ['Country','GDP (Million USD)']
df

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [17]:
# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
df['GDP (Million USD)'] = df['GDP (Million USD)'].astype(int)
df

           Country  GDP (Million USD)
1    United States           26854599
2            China           19373586
3            Japan            4409738
4          Germany            4308854
5            India            3736882
6   United Kingdom            3158938
7           France            2923489
8            Italy            2169745
9           Canada            2089672
10          Brazil            2081235

In [18]:
# Convert the GDP value in Million USD to Billion USD
df[['GDP (Million USD)']] = df[['GDP (Million USD)']]/1000
df

           Country  GDP (Million USD)
1    United States          26854.599
2            China          19373.586
3            Japan           4409.738
4          Germany           4308.854
5            India           3736.882
6   United Kingdom           3158.938
7           France           2923.489
8            Italy           2169.745
9           Canada           2089.672
10          Brazil           2081.235

In [19]:
# Use numpy.round() method to round the value to 2 decimal places.
df[['GDP (Million USD)']] = np.round(df[['GDP (Million USD)']], 2)
df

           Country  GDP (Million USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [20]:
# Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'
df.rename(columns = {'GDP (Million USD)' : 'GDP (Billion USD)'})

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [21]:
df.to_csv('/Users/yarahatemibrahim/Desktop/Largest_economies.csv')